var toc = {"link":"toc","title":"toc","children":[{"link":"null","title":"UnityEngine","children":
	[
		{"link":"null","title":"UnityEngine.Events","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"Events.UnityEvent","title":"UnityEvent","children":null},
			{"link":"Events.UnityEvent_1","title":"UnityEvent<T0>","children":null},
			{"link":"Events.UnityEvent_2","title":"UnityEvent<T0,T1>","children":null},
			{"link":"Events.UnityEvent_3","title":"UnityEvent<T0,T1,T2>","children":null},
			{"link":"Events.UnityEvent_4","title":"UnityEvent<T0,T1,T2,T3>","children":null},
			{"link":"Events.UnityEventBase","title":"UnityEventBase","children":null}
		]
	},
	{"link":"null","title":"Enumerations","children":
		[
					{"link":"Events.PersistentListenerMode","title":"PersistentListenerMode","children":null},
			{"link":"Events.UnityEventCallState","title":"UnityEventCallState","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEngine.EventSystems","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"EventSystems.AxisEventData","title":"AxisEventData","children":null},
			{"link":"EventSystems.BaseEventData","title":"BaseEventData","children":null},
			{"link":"EventSystems.BaseInputModule","title":"BaseInputModule","children":null},
			{"link":"EventSystems.BaseRaycaster","title":"BaseRaycaster","children":null},
			{"link":"EventSystems.EventSystem","title":"EventSystem","children":null},
			{"link":"EventSystems.EventTrigger","title":"EventTrigger","children":null},
			{"link":"EventSystems.EventTrigger.Entry","title":"Entry","children":null},
			{"link":"EventSystems.EventTrigger.TriggerEvent","title":"TriggerEvent","children":null},
			{"link":"EventSystems.ExecuteEvents","title":"ExecuteEvents","children":null},
			{"link":"EventSystems.Physics2DRaycaster","title":"Physics2DRaycaster","children":null},
			{"link":"EventSystems.PhysicsRaycaster","title":"PhysicsRaycaster","children":null},
			{"link":"EventSystems.PointerEventData","title":"PointerEventData","children":null},
			{"link":"EventSystems.PointerInputModule","title":"PointerInputModule","children":null},
			{"link":"EventSystems.PointerInputModule.MouseButtonEventData","title":"MouseButtonEventData","children":null},
			{"link":"EventSystems.RaycastResult","title":"RaycastResult","children":null},
			{"link":"EventSystems.StandaloneInputModule","title":"StandaloneInputModule","children":null},
			{"link":"EventSystems.TouchInputModule","title":"TouchInputModule","children":null},
			{"link":"EventSystems.UIBehaviour","title":"UIBehaviour","children":null}
		]
	},
	{"link":"null","title":"Enumerations","children":
		[
					{"link":"EventSystems.EventHandle","title":"EventHandle","children":null},
			{"link":"EventSystems.EventTriggerType","title":"EventTriggerType","children":null},
			{"link":"EventSystems.MoveDirection","title":"MoveDirection","children":null},
			{"link":"EventSystems.PointerEventData.FramePressState","title":"FramePressState","children":null},
			{"link":"EventSystems.PointerEventData.InputButton","title":"InputButton","children":null},
			{"link":"EventSystems.StandaloneInputModule.InputMode","title":"InputMode","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEngine.Flash","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"Flash.ActionScript","title":"ActionScript","children":null},
			{"link":"Flash.FlashPlayer","title":"FlashPlayer","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEngine.Rendering","children":
		[
			{"link":"null","title":"Enumerations","children":
		[
					{"link":"Rendering.BlendMode","title":"BlendMode","children":null},
			{"link":"Rendering.BlendOp","title":"BlendOp","children":null},
			{"link":"Rendering.ColorWriteMask","title":"ColorWriteMask","children":null},
			{"link":"Rendering.CompareFunction","title":"CompareFunction","children":null},
			{"link":"Rendering.CullMode","title":"CullMode","children":null},
			{"link":"Rendering.StencilOp","title":"StencilOp","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEngine.Serialization","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"Serialization.PPtrRemapper","title":"PPtrRemapper","children":null},
			{"link":"Serialization.SerializedStateReader","title":"SerializedStateReader","children":null},
			{"link":"Serialization.SerializedStateWriter","title":"SerializedStateWriter","children":null}
		]
	},
	{"link":"null","title":"Attributes","children":
		[
					{"link":"Serialization.FormerlySerializedAsAttribute","title":"FormerlySerializedAsAttribute","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEngine.SocialPlatforms","children":
		[
				{"link":"null","title":"UnityEngine.SocialPlatforms.GameCenter","children":
			[
					{"link":"null","title":"Classes","children":
			[
							{"link":"SocialPlatforms.GameCenter.GameCenterPlatform","title":"GameCenterPlatform","children":null}
			]
		}
			]
		},
		{"link":"null","title":"UnityEngine.SocialPlatforms.Impl","children":
			[
					{"link":"null","title":"Classes","children":
			[
							{"link":"SocialPlatforms.Impl.Achievement","title":"Achievement","children":null},
				{"link":"SocialPlatforms.Impl.AchievementDescription","title":"AchievementDescription","children":null},
				{"link":"SocialPlatforms.Impl.Leaderboard","title":"Leaderboard","children":null},
				{"link":"SocialPlatforms.Impl.LocalUser","title":"LocalUser","children":null},
				{"link":"SocialPlatforms.Impl.Score","title":"Score","children":null},
				{"link":"SocialPlatforms.Impl.UserProfile","title":"UserProfile","children":null}
			]
		}
			]
		},
	{"link":"null","title":"Classes","children":
		[
					{"link":"SocialPlatforms.Local","title":"Local","children":null},
			{"link":"SocialPlatforms.Range","title":"Range","children":null}
		]
	},
	{"link":"null","title":"Enumerations","children":
		[
					{"link":"SocialPlatforms.TimeScope","title":"TimeScope","children":null},
			{"link":"SocialPlatforms.UserScope","title":"UserScope","children":null},
			{"link":"SocialPlatforms.UserState","title":"UserState","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEngine.Sprites","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"Sprites.DataUtility","title":"DataUtility","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEngine.UI","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"UI.AnimationTriggers","title":"AnimationTriggers","children":null},
			{"link":"UI.AspectRatioFitter","title":"AspectRatioFitter","children":null},
			{"link":"UI.BaseVertexEffect","title":"BaseVertexEffect","children":null},
			{"link":"UI.Button","title":"Button","children":null},
			{"link":"UI.Button.ButtonClickedEvent","title":"ButtonClickedEvent","children":null},
			{"link":"UI.CanvasScaler","title":"CanvasScaler","children":null},
			{"link":"UI.CanvasUpdateRegistry","title":"CanvasUpdateRegistry","children":null},
			{"link":"UI.ColorBlock","title":"ColorBlock","children":null},
			{"link":"UI.ContentSizeFitter","title":"ContentSizeFitter","children":null},
			{"link":"UI.FontData","title":"FontData","children":null},
			{"link":"UI.Graphic","title":"Graphic","children":null},
			{"link":"UI.GraphicRaycaster","title":"GraphicRaycaster","children":null},
			{"link":"UI.GraphicRegistry","title":"GraphicRegistry","children":null},
			{"link":"UI.GridLayoutGroup","title":"GridLayoutGroup","children":null},
			{"link":"UI.HorizontalLayoutGroup","title":"HorizontalLayoutGroup","children":null},
			{"link":"UI.HorizontalOrVerticalLayoutGroup","title":"HorizontalOrVerticalLayoutGroup","children":null},
			{"link":"UI.Image","title":"Image","children":null},
			{"link":"UI.InputField","title":"InputField","children":null},
			{"link":"UI.InputField.OnChangeEvent","title":"OnChangeEvent","children":null},
			{"link":"UI.InputField.SubmitEvent","title":"SubmitEvent","children":null},
			{"link":"UI.LayoutElement","title":"LayoutElement","children":null},
			{"link":"UI.LayoutGroup","title":"LayoutGroup","children":null},
			{"link":"UI.LayoutRebuilder","title":"LayoutRebuilder","children":null},
			{"link":"UI.LayoutUtility","title":"LayoutUtility","children":null},
			{"link":"UI.Mask","title":"Mask","children":null},
			{"link":"UI.MaskableGraphic","title":"MaskableGraphic","children":null},
			{"link":"UI.Navigation","title":"Navigation","children":null},
			{"link":"UI.Outline","title":"Outline","children":null},
			{"link":"UI.PositionAsUV1","title":"PositionAsUV1","children":null},
			{"link":"UI.RawImage","title":"RawImage","children":null},
			{"link":"UI.Scrollbar","title":"Scrollbar","children":null},
			{"link":"UI.Scrollbar.ScrollEvent","title":"ScrollEvent","children":null},
			{"link":"UI.ScrollRect","title":"ScrollRect","children":null},
			{"link":"UI.ScrollRect.ScrollRectEvent","title":"ScrollRectEvent","children":null},
			{"link":"UI.Selectable","title":"Selectable","children":null},
			{"link":"UI.Shadow","title":"Shadow","children":null},
			{"link":"UI.Slider","title":"Slider","children":null},
			{"link":"UI.Slider.SliderEvent","title":"SliderEvent","children":null},
			{"link":"UI.SpriteState","title":"SpriteState","children":null},
			{"link":"UI.Text","title":"Text","children":null},
			{"link":"UI.Toggle","title":"Toggle","children":null},
			{"link":"UI.Toggle.ToggleEvent","title":"ToggleEvent","children":null},
			{"link":"UI.ToggleGroup","title":"ToggleGroup","children":null},
			{"link":"UI.VerticalLayoutGroup","title":"VerticalLayoutGroup","children":null}
		]
	},
	{"link":"null","title":"Enumerations","children":
		[
					{"link":"UI.AspectRatioFitter.AspectMode","title":"AspectMode","children":null},
			{"link":"UI.CanvasScaler.ScaleMode","title":"ScaleMode","children":null},
			{"link":"UI.CanvasScaler.ScreenMatchMode","title":"ScreenMatchMode","children":null},
			{"link":"UI.CanvasScaler.Unit","title":"Unit","children":null},
			{"link":"UI.CanvasUpdate","title":"CanvasUpdate","children":null},
			{"link":"UI.ContentSizeFitter.FitMode","title":"FitMode","children":null},
			{"link":"UI.GraphicRaycaster.BlockingObjects","title":"BlockingObjects","children":null},
			{"link":"UI.GridLayoutGroup.Axis","title":"Axis","children":null},
			{"link":"UI.GridLayoutGroup.Constraint","title":"Constraint","children":null},
			{"link":"UI.GridLayoutGroup.Corner","title":"Corner","children":null},
			{"link":"UI.Image.FillMethod","title":"FillMethod","children":null},
			{"link":"UI.Image.Origin180","title":"Origin180","children":null},
			{"link":"UI.Image.Origin360","title":"Origin360","children":null},
			{"link":"UI.Image.Origin90","title":"Origin90","children":null},
			{"link":"UI.Image.OriginHorizontal","title":"OriginHorizontal","children":null},
			{"link":"UI.Image.OriginVertical","title":"OriginVertical","children":null},
			{"link":"UI.Image.Type","title":"Type","children":null},
			{"link":"UI.InputField.CharacterValidation","title":"CharacterValidation","children":null},
			{"link":"UI.InputField.ContentType","title":"ContentType","children":null},
			{"link":"UI.InputField.InputType","title":"InputType","children":null},
			{"link":"UI.InputField.LineType","title":"LineType","children":null},
			{"link":"UI.Navigation.Mode","title":"Mode","children":null},
			{"link":"UI.Scrollbar.Direction","title":"Direction","children":null},
			{"link":"UI.ScrollRect.MovementType","title":"MovementType","children":null},
			{"link":"UI.Selectable.Transition","title":"Transition","children":null},
			{"link":"UI.Slider.Direction","title":"Direction","children":null},
			{"link":"UI.Toggle.ToggleTransition","title":"ToggleTransition","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEngine.Windows","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"Windows.Crypto","title":"Crypto","children":null},
			{"link":"Windows.Directory","title":"Directory","children":null},
			{"link":"Windows.File","title":"File","children":null},
			{"link":"Windows.LicenseInformation","title":"LicenseInformation","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEngine.WindowsPhone","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"WindowsPhone.EventProvider","title":"EventProvider","children":null},
			{"link":"WindowsPhone.Media","title":"Media","children":null}
		]
	},
	{"link":"null","title":"Enumerations","children":
		[
					{"link":"WindowsPhone.Media.MediaState","title":"MediaState","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEngine.WSA","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"WSA.Application","title":"Application","children":null},
			{"link":"WSA.Cursor","title":"Cursor","children":null},
			{"link":"WSA.Launcher","title":"Launcher","children":null},
			{"link":"WSA.SecondaryTileData","title":"SecondaryTileData","children":null},
			{"link":"WSA.Tile","title":"Tile","children":null},
			{"link":"WSA.Toast","title":"Toast","children":null}
		]
	},
	{"link":"null","title":"Enumerations","children":
		[
					{"link":"WSA.Folder","title":"Folder","children":null},
			{"link":"WSA.TileForegroundText","title":"TileForegroundText","children":null},
			{"link":"WSA.TileTemplate","title":"TileTemplate","children":null},
			{"link":"WSA.ToastTemplate","title":"ToastTemplate","children":null},
			{"link":"WSA.WindowActivationState","title":"WindowActivationState","children":null}
		]
	}
		]
	},
{"link":"null","title":"Classes","children":
	[
			{"link":"AccelerationEvent","title":"AccelerationEvent","children":null},
		{"link":"ADBannerView","title":"ADBannerView","children":null},
		{"link":"AddComponentMenu","title":"AddComponentMenu","children":null},
		{"link":"ADInterstitialAd","title":"ADInterstitialAd","children":null},
		{"link":"AnchoredJoint2D","title":"AnchoredJoint2D","children":null},
		{"link":"AndroidInput","title":"AndroidInput","children":null},
		{"link":"AndroidJavaClass","title":"AndroidJavaClass","children":null},
		{"link":"AndroidJavaException","title":"AndroidJavaException","children":null},
		{"link":"AndroidJavaObject","title":"AndroidJavaObject","children":null},
		{"link":"AndroidJavaProxy","title":"AndroidJavaProxy","children":null},
		{"link":"AndroidJNI","title":"AndroidJNI","children":null},
		{"link":"AndroidJNIHelper","title":"AndroidJNIHelper","children":null},
		{"link":"Animation","title":"Animation","children":null},
		{"link":"AnimationClip","title":"AnimationClip","children":null},
		{"link":"AnimationClipPair","title":"AnimationClipPair","children":null},
		{"link":"AnimationCurve","title":"AnimationCurve","children":null},
		{"link":"AnimationEvent","title":"AnimationEvent","children":null},
		{"link":"AnimationInfo","title":"AnimationInfo","children":null},
		{"link":"AnimationState","title":"AnimationState","children":null},
		{"link":"Animator","title":"Animator","children":null},
		{"link":"AnimatorOverrideController","title":"AnimatorOverrideController","children":null},
		{"link":"AnimatorStateInfo","title":"AnimatorStateInfo","children":null},
		{"link":"AnimatorTransitionInfo","title":"AnimatorTransitionInfo","children":null},
		{"link":"AnimatorUtility","title":"AnimatorUtility","children":null},
		{"link":"Application","title":"Application","children":null},
		{"link":"AssemblyIsEditorAssembly","title":"AssemblyIsEditorAssembly","children":null},
		{"link":"AssetBundle","title":"AssetBundle","children":null},
		{"link":"AssetBundleCreateRequest","title":"AssetBundleCreateRequest","children":null},
		{"link":"AssetBundleRequest","title":"AssetBundleRequest","children":null},
		{"link":"AsyncOperation","title":"AsyncOperation","children":null},
		{"link":"AudioChorusFilter","title":"AudioChorusFilter","children":null},
		{"link":"AudioClip","title":"AudioClip","children":null},
		{"link":"AudioDistortionFilter","title":"AudioDistortionFilter","children":null},
		{"link":"AudioEchoFilter","title":"AudioEchoFilter","children":null},
		{"link":"AudioHighPassFilter","title":"AudioHighPassFilter","children":null},
		{"link":"AudioListener","title":"AudioListener","children":null},
		{"link":"AudioLowPassFilter","title":"AudioLowPassFilter","children":null},
		{"link":"AudioReverbFilter","title":"AudioReverbFilter","children":null},
		{"link":"AudioReverbZone","title":"AudioReverbZone","children":null},
		{"link":"AudioSettings","title":"AudioSettings","children":null},
		{"link":"AudioSource","title":"AudioSource","children":null},
		{"link":"Avatar","title":"Avatar","children":null},
		{"link":"AvatarBuilder","title":"AvatarBuilder","children":null},
		{"link":"Behaviour","title":"Behaviour","children":null},
		{"link":"BitStream","title":"BitStream","children":null},
		{"link":"BoneWeight","title":"BoneWeight","children":null},
		{"link":"Bounds","title":"Bounds","children":null},
		{"link":"BoxCollider","title":"BoxCollider","children":null},
		{"link":"BoxCollider2D","title":"BoxCollider2D","children":null},
		{"link":"Caching","title":"Caching","children":null},
		{"link":"Camera","title":"Camera","children":null},
		{"link":"Canvas","title":"Canvas","children":null},
		{"link":"CanvasGroup","title":"CanvasGroup","children":null},
		{"link":"CanvasRenderer","title":"CanvasRenderer","children":null},
		{"link":"CapsuleCollider","title":"CapsuleCollider","children":null},
		{"link":"CharacterController","title":"CharacterController","children":null},
		{"link":"CharacterInfo","title":"CharacterInfo","children":null},
		{"link":"CharacterJoint","title":"CharacterJoint","children":null},
		{"link":"CircleCollider2D","title":"CircleCollider2D","children":null},
		{"link":"Cloth","title":"Cloth","children":null},
		{"link":"ClothRenderer","title":"ClothRenderer","children":null},
		{"link":"ClothSkinningCoefficient","title":"ClothSkinningCoefficient","children":null},
		{"link":"Collider","title":"Collider","children":null},
		{"link":"Collider2D","title":"Collider2D","children":null},
		{"link":"Collision","title":"Collision","children":null},
		{"link":"Collision2D","title":"Collision2D","children":null},
		{"link":"Color","title":"Color","children":null},
		{"link":"Color32","title":"Color32","children":null},
		{"link":"CombineInstance","title":"CombineInstance","children":null},
		{"link":"Compass","title":"Compass","children":null},
		{"link":"Component","title":"Component","children":null},
		{"link":"ComputeBuffer","title":"ComputeBuffer","children":null},
		{"link":"ComputeShader","title":"ComputeShader","children":null},
		{"link":"ConfigurableJoint","title":"ConfigurableJoint","children":null},
		{"link":"ConstantForce","title":"ConstantForce","children":null},
		{"link":"ContactPoint","title":"ContactPoint","children":null},
		{"link":"ContactPoint2D","title":"ContactPoint2D","children":null},
		{"link":"ContextMenu","title":"ContextMenu","children":null},
		{"link":"ControllerColliderHit","title":"ControllerColliderHit","children":null},
		{"link":"Coroutine","title":"Coroutine","children":null},
		{"link":"CrashReport","title":"CrashReport","children":null},
		{"link":"Cubemap","title":"Cubemap","children":null},
		{"link":"Cursor","title":"Cursor","children":null},
		{"link":"Debug","title":"Debug","children":null},
		{"link":"DetailPrototype","title":"DetailPrototype","children":null},
		{"link":"DisallowMultipleComponent","title":"DisallowMultipleComponent","children":null},
		{"link":"Display","title":"Display","children":null},
		{"link":"DistanceJoint2D","title":"DistanceJoint2D","children":null},
		{"link":"DrivenRectTransformTracker","title":"DrivenRectTransformTracker","children":null},
		{"link":"EdgeCollider2D","title":"EdgeCollider2D","children":null},
		{"link":"Event","title":"Event","children":null},
		{"link":"ExecuteInEditMode","title":"ExecuteInEditMode","children":null},
		{"link":"FixedJoint","title":"FixedJoint","children":null},
		{"link":"Flare","title":"Flare","children":null},
		{"link":"Font","title":"Font","children":null},
		{"link":"GameObject","title":"GameObject","children":null},
		{"link":"GeometryUtility","title":"GeometryUtility","children":null},
		{"link":"Gizmos","title":"Gizmos","children":null},
		{"link":"GL","title":"GL","children":null},
		{"link":"Gradient","title":"Gradient","children":null},
		{"link":"GradientAlphaKey","title":"GradientAlphaKey","children":null},
		{"link":"GradientColorKey","title":"GradientColorKey","children":null},
		{"link":"Graphics","title":"Graphics","children":null},
		{"link":"GUI","title":"GUI","children":null},
		{"link":"GUIContent","title":"GUIContent","children":null},
		{"link":"GUIElement","title":"GUIElement","children":null},
		{"link":"GUILayer","title":"GUILayer","children":null},
		{"link":"GUILayout","title":"GUILayout","children":null},
		{"link":"GUILayoutOption","title":"GUILayoutOption","children":null},
		{"link":"GUILayoutUtility","title":"GUILayoutUtility","children":null},
		{"link":"GUISettings","title":"GUISettings","children":null},
		{"link":"GUISkin","title":"GUISkin","children":null},
		{"link":"GUIStyle","title":"GUIStyle","children":null},
		{"link":"GUIStyleState","title":"GUIStyleState","children":null},
		{"link":"GUIText","title":"GUIText","children":null},
		{"link":"GUITexture","title":"GUITexture","children":null},
		{"link":"GUIUtility","title":"GUIUtility","children":null},
		{"link":"Gyroscope","title":"Gyroscope","children":null},
		{"link":"Handheld","title":"Handheld","children":null},
		{"link":"HideInInspector","title":"HideInInspector","children":null},
		{"link":"HingeJoint","title":"HingeJoint","children":null},
		{"link":"HingeJoint2D","title":"HingeJoint2D","children":null},
		{"link":"HostData","title":"HostData","children":null},
		{"link":"HumanBone","title":"HumanBone","children":null},
		{"link":"HumanDescription","title":"HumanDescription","children":null},
		{"link":"HumanLimit","title":"HumanLimit","children":null},
		{"link":"HumanTrait","title":"HumanTrait","children":null},
		{"link":"ImageEffectOpaque","title":"ImageEffectOpaque","children":null},
		{"link":"ImageEffectTransformsToLDR","title":"ImageEffectTransformsToLDR","children":null},
		{"link":"Input","title":"Input","children":null},
		{"link":"InteractiveCloth","title":"InteractiveCloth","children":null},
		{"link":"iPhone","title":"iPhone","children":null},
		{"link":"iPhone.NSError","title":"NSError","children":null},
		{"link":"iPhone.NSNotification","title":"NSNotification","children":null},
		{"link":"iPhoneInput","title":"iPhoneInput","children":null},
		{"link":"Joint","title":"Joint","children":null},
		{"link":"Joint2D","title":"Joint2D","children":null},
		{"link":"JointAngleLimits2D","title":"JointAngleLimits2D","children":null},
		{"link":"JointDrive","title":"JointDrive","children":null},
		{"link":"JointLimits","title":"JointLimits","children":null},
		{"link":"JointMotor","title":"JointMotor","children":null},
		{"link":"JointMotor2D","title":"JointMotor2D","children":null},
		{"link":"JointSpring","title":"JointSpring","children":null},
		{"link":"JointSuspension2D","title":"JointSuspension2D","children":null},
		{"link":"JointTranslationLimits2D","title":"JointTranslationLimits2D","children":null},
		{"link":"Keyframe","title":"Keyframe","children":null},
		{"link":"LayerMask","title":"LayerMask","children":null},
		{"link":"LensFlare","title":"LensFlare","children":null},
		{"link":"Light","title":"Light","children":null},
		{"link":"LightmapData","title":"LightmapData","children":null},
		{"link":"LightmapSettings","title":"LightmapSettings","children":null},
		{"link":"LightProbeGroup","title":"LightProbeGroup","children":null},
		{"link":"LightProbes","title":"LightProbes","children":null},
		{"link":"LineRenderer","title":"LineRenderer","children":null},
		{"link":"LocalNotification","title":"LocalNotification","children":null},
		{"link":"LocationInfo","title":"LocationInfo","children":null},
		{"link":"LocationService","title":"LocationService","children":null},
		{"link":"LOD","title":"LOD","children":null},
		{"link":"LODGroup","title":"LODGroup","children":null},
		{"link":"MasterServer","title":"MasterServer","children":null},
		{"link":"MatchTargetWeightMask","title":"MatchTargetWeightMask","children":null},
		{"link":"Material","title":"Material","children":null},
		{"link":"MaterialPropertyBlock","title":"MaterialPropertyBlock","children":null},
		{"link":"Mathf","title":"Mathf","children":null},
		{"link":"Matrix4x4","title":"Matrix4x4","children":null},
		{"link":"Mesh","title":"Mesh","children":null},
		{"link":"MeshCollider","title":"MeshCollider","children":null},
		{"link":"MeshFilter","title":"MeshFilter","children":null},
		{"link":"MeshRenderer","title":"MeshRenderer","children":null},
		{"link":"Microphone","title":"Microphone","children":null},
		{"link":"MissingComponentException","title":"MissingComponentException","children":null},
		{"link":"MissingReferenceException","title":"MissingReferenceException","children":null},
		{"link":"MonoBehaviour","title":"MonoBehaviour","children":null},
		{"link":"Motion","title":"Motion","children":null},
		{"link":"MovieTexture","title":"MovieTexture","children":null},
		{"link":"NavMesh","title":"NavMesh","children":null},
		{"link":"NavMeshAgent","title":"NavMeshAgent","children":null},
		{"link":"NavMeshHit","title":"NavMeshHit","children":null},
		{"link":"NavMeshObstacle","title":"NavMeshObstacle","children":null},
		{"link":"NavMeshPath","title":"NavMeshPath","children":null},
		{"link":"NavMeshTriangulation","title":"NavMeshTriangulation","children":null},
		{"link":"Network","title":"Network","children":null},
		{"link":"NetworkMessageInfo","title":"NetworkMessageInfo","children":null},
		{"link":"NetworkPlayer","title":"NetworkPlayer","children":null},
		{"link":"NetworkView","title":"NetworkView","children":null},
		{"link":"NetworkViewID","title":"NetworkViewID","children":null},
		{"link":"NotificationServices","title":"NotificationServices","children":null},
		{"link":"Object","title":"Object","children":null},
		{"link":"OcclusionArea","title":"OcclusionArea","children":null},
		{"link":"OcclusionPortal","title":"OcclusionPortal","children":null},
		{"link":"OffMeshLink","title":"OffMeshLink","children":null},
		{"link":"OffMeshLinkData","title":"OffMeshLinkData","children":null},
		{"link":"Particle","title":"Particle","children":null},
		{"link":"ParticleAnimator","title":"ParticleAnimator","children":null},
		{"link":"ParticleEmitter","title":"ParticleEmitter","children":null},
		{"link":"ParticleRenderer","title":"ParticleRenderer","children":null},
		{"link":"ParticleSystem","title":"ParticleSystem","children":null},
		{"link":"ParticleSystem.CollisionEvent","title":"CollisionEvent","children":null},
		{"link":"ParticleSystem.Particle","title":"Particle","children":null},
		{"link":"ParticleSystemRenderer","title":"ParticleSystemRenderer","children":null},
		{"link":"PhysicMaterial","title":"PhysicMaterial","children":null},
		{"link":"Physics","title":"Physics","children":null},
		{"link":"Physics2D","title":"Physics2D","children":null},
		{"link":"PhysicsMaterial2D","title":"PhysicsMaterial2D","children":null},
		{"link":"Ping","title":"Ping","children":null},
		{"link":"Plane","title":"Plane","children":null},
		{"link":"PlayerPrefs","title":"PlayerPrefs","children":null},
		{"link":"PlayerPrefsException","title":"PlayerPrefsException","children":null},
		{"link":"PolygonCollider2D","title":"PolygonCollider2D","children":null},
		{"link":"ProceduralMaterial","title":"ProceduralMaterial","children":null},
		{"link":"ProceduralPropertyDescription","title":"ProceduralPropertyDescription","children":null},
		{"link":"ProceduralTexture","title":"ProceduralTexture","children":null},
		{"link":"Profiler","title":"Profiler","children":null},
		{"link":"Projector","title":"Projector","children":null},
		{"link":"QualitySettings","title":"QualitySettings","children":null},
		{"link":"Quaternion","title":"Quaternion","children":null},
		{"link":"Random","title":"Random","children":null},
		{"link":"Ray","title":"Ray","children":null},
		{"link":"Ray2D","title":"Ray2D","children":null},
		{"link":"RaycastHit","title":"RaycastHit","children":null},
		{"link":"RaycastHit2D","title":"RaycastHit2D","children":null},
		{"link":"Rect","title":"Rect","children":null},
		{"link":"RectOffset","title":"RectOffset","children":null},
		{"link":"RectTransform","title":"RectTransform","children":null},
		{"link":"RectTransformUtility","title":"RectTransformUtility","children":null},
		{"link":"RemoteNotification","title":"RemoteNotification","children":null},
		{"link":"RenderBuffer","title":"RenderBuffer","children":null},
		{"link":"Renderer","title":"Renderer","children":null},
		{"link":"RenderSettings","title":"RenderSettings","children":null},
		{"link":"RenderTexture","title":"RenderTexture","children":null},
		{"link":"RequireComponent","title":"RequireComponent","children":null},
		{"link":"Resolution","title":"Resolution","children":null},
		{"link":"ResourceRequest","title":"ResourceRequest","children":null},
		{"link":"Resources","title":"Resources","children":null},
		{"link":"Rigidbody","title":"Rigidbody","children":null},
		{"link":"Rigidbody2D","title":"Rigidbody2D","children":null},
		{"link":"RPC","title":"RPC","children":null},
		{"link":"RuntimeAnimatorController","title":"RuntimeAnimatorController","children":null},
		{"link":"SamsungTV","title":"SamsungTV","children":null},
		{"link":"Screen","title":"Screen","children":null},
		{"link":"ScriptableObject","title":"ScriptableObject","children":null},
		{"link":"Security","title":"Security","children":null},
		{"link":"SerializeField","title":"SerializeField","children":null},
		{"link":"Shader","title":"Shader","children":null},
		{"link":"SkeletonBone","title":"SkeletonBone","children":null},
		{"link":"SkinnedCloth","title":"SkinnedCloth","children":null},
		{"link":"SkinnedMeshRenderer","title":"SkinnedMeshRenderer","children":null},
		{"link":"Skybox","title":"Skybox","children":null},
		{"link":"SleepTimeout","title":"SleepTimeout","children":null},
		{"link":"SliderJoint2D","title":"SliderJoint2D","children":null},
		{"link":"Social","title":"Social","children":null},
		{"link":"SoftJointLimit","title":"SoftJointLimit","children":null},
		{"link":"SparseTexture","title":"SparseTexture","children":null},
		{"link":"SphereCollider","title":"SphereCollider","children":null},
		{"link":"SplatPrototype","title":"SplatPrototype","children":null},
		{"link":"SpringJoint","title":"SpringJoint","children":null},
		{"link":"SpringJoint2D","title":"SpringJoint2D","children":null},
		{"link":"Sprite","title":"Sprite","children":null},
		{"link":"SpriteRenderer","title":"SpriteRenderer","children":null},
		{"link":"StackTraceUtility","title":"StackTraceUtility","children":null},
		{"link":"StaticBatchingUtility","title":"StaticBatchingUtility","children":null},
		{"link":"SystemInfo","title":"SystemInfo","children":null},
		{"link":"Terrain","title":"Terrain","children":null},
		{"link":"TerrainCollider","title":"TerrainCollider","children":null},
		{"link":"TerrainData","title":"TerrainData","children":null},
		{"link":"TextAsset","title":"TextAsset","children":null},
		{"link":"TextEditor","title":"TextEditor","children":null},
		{"link":"TextGenerationSettings","title":"TextGenerationSettings","children":null},
		{"link":"TextGenerator","title":"TextGenerator","children":null},
		{"link":"TextMesh","title":"TextMesh","children":null},
		{"link":"Texture","title":"Texture","children":null},
		{"link":"Texture2D","title":"Texture2D","children":null},
		{"link":"Texture3D","title":"Texture3D","children":null},
		{"link":"Time","title":"Time","children":null},
		{"link":"Touch","title":"Touch","children":null},
		{"link":"TouchScreenKeyboard","title":"TouchScreenKeyboard","children":null},
		{"link":"TrackedReference","title":"TrackedReference","children":null},
		{"link":"TrailRenderer","title":"TrailRenderer","children":null},
		{"link":"Transform","title":"Transform","children":null},
		{"link":"Tree","title":"Tree","children":null},
		{"link":"TreeInstance","title":"TreeInstance","children":null},
		{"link":"TreePrototype","title":"TreePrototype","children":null},
		{"link":"Types","title":"Types","children":null},
		{"link":"UICharInfo","title":"UICharInfo","children":null},
		{"link":"UILineInfo","title":"UILineInfo","children":null},
		{"link":"UIVertex","title":"UIVertex","children":null},
		{"link":"UnassignedReferenceException","title":"UnassignedReferenceException","children":null},
		{"link":"UnityException","title":"UnityException","children":null},
		{"link":"Vector2","title":"Vector2","children":null},
		{"link":"Vector3","title":"Vector3","children":null},
		{"link":"Vector4","title":"Vector4","children":null},
		{"link":"WaitForEndOfFrame","title":"WaitForEndOfFrame","children":null},
		{"link":"WaitForFixedUpdate","title":"WaitForFixedUpdate","children":null},
		{"link":"WaitForSeconds","title":"WaitForSeconds","children":null},
		{"link":"WebCamDevice","title":"WebCamDevice","children":null},
		{"link":"WebCamTexture","title":"WebCamTexture","children":null},
		{"link":"WheelCollider","title":"WheelCollider","children":null},
		{"link":"WheelFrictionCurve","title":"WheelFrictionCurve","children":null},
		{"link":"WheelHit","title":"WheelHit","children":null},
		{"link":"WheelJoint2D","title":"WheelJoint2D","children":null},
		{"link":"WWW","title":"WWW","children":null},
		{"link":"WWWForm","title":"WWWForm","children":null},
		{"link":"YieldInstruction","title":"YieldInstruction","children":null}
	]
},
{"link":"null","title":"Enumerations","children":
	[
			{"link":"ADBannerView.Layout","title":"Layout","children":null},
		{"link":"ADBannerView.Type","title":"Type","children":null},
		{"link":"AndroidActivityIndicatorStyle","title":"AndroidActivityIndicatorStyle","children":null},
		{"link":"AnimationBlendMode","title":"AnimationBlendMode","children":null},
		{"link":"AnimationCullingType","title":"AnimationCullingType","children":null},
		{"link":"AnimatorCullingMode","title":"AnimatorCullingMode","children":null},
		{"link":"AnimatorUpdateMode","title":"AnimatorUpdateMode","children":null},
		{"link":"AnisotropicFiltering","title":"AnisotropicFiltering","children":null},
		{"link":"AudioReverbPreset","title":"AudioReverbPreset","children":null},
		{"link":"AudioRolloffMode","title":"AudioRolloffMode","children":null},
		{"link":"AudioSpeakerMode","title":"AudioSpeakerMode","children":null},
		{"link":"AudioType","title":"AudioType","children":null},
		{"link":"AudioVelocityUpdateMode","title":"AudioVelocityUpdateMode","children":null},
		{"link":"AvatarIKGoal","title":"AvatarIKGoal","children":null},
		{"link":"AvatarTarget","title":"AvatarTarget","children":null},
		{"link":"BlendWeights","title":"BlendWeights","children":null},
		{"link":"CalendarIdentifier","title":"CalendarIdentifier","children":null},
		{"link":"CalendarUnit","title":"CalendarUnit","children":null},
		{"link":"CameraClearFlags","title":"CameraClearFlags","children":null},
		{"link":"CollisionDetectionMode","title":"CollisionDetectionMode","children":null},
		{"link":"CollisionDetectionMode2D","title":"CollisionDetectionMode2D","children":null},
		{"link":"CollisionFlags","title":"CollisionFlags","children":null},
		{"link":"ColorSpace","title":"ColorSpace","children":null},
		{"link":"ComputeBufferType","title":"ComputeBufferType","children":null},
		{"link":"ConfigurableJointMotion","title":"ConfigurableJointMotion","children":null},
		{"link":"ConnectionTesterStatus","title":"ConnectionTesterStatus","children":null},
		{"link":"CubemapFace","title":"CubemapFace","children":null},
		{"link":"CursorMode","title":"CursorMode","children":null},
		{"link":"DepthTextureMode","title":"DepthTextureMode","children":null},
		{"link":"DetailRenderMode","title":"DetailRenderMode","children":null},
		{"link":"DeviceOrientation","title":"DeviceOrientation","children":null},
		{"link":"DeviceType","title":"DeviceType","children":null},
		{"link":"DrivenTransformProperties","title":"DrivenTransformProperties","children":null},
		{"link":"EventModifiers","title":"EventModifiers","children":null},
		{"link":"EventType","title":"EventType","children":null},
		{"link":"FFTWindow","title":"FFTWindow","children":null},
		{"link":"FilterMode","title":"FilterMode","children":null},
		{"link":"FocusType","title":"FocusType","children":null},
		{"link":"FogMode","title":"FogMode","children":null},
		{"link":"FontStyle","title":"FontStyle","children":null},
		{"link":"ForceMode","title":"ForceMode","children":null},
		{"link":"ForceMode2D","title":"ForceMode2D","children":null},
		{"link":"FullScreenMovieControlMode","title":"FullScreenMovieControlMode","children":null},
		{"link":"FullScreenMovieScalingMode","title":"FullScreenMovieScalingMode","children":null},
		{"link":"HideFlags","title":"HideFlags","children":null},
		{"link":"HorizontalWrapMode","title":"HorizontalWrapMode","children":null},
		{"link":"HumanBodyBones","title":"HumanBodyBones","children":null},
		{"link":"ImagePosition","title":"ImagePosition","children":null},
		{"link":"IMECompositionMode","title":"IMECompositionMode","children":null},
		{"link":"iOSActivityIndicatorStyle","title":"iOSActivityIndicatorStyle","children":null},
		{"link":"iPhoneGeneration","title":"iPhoneGeneration","children":null},
		{"link":"JointDriveMode","title":"JointDriveMode","children":null},
		{"link":"JointLimitState2D","title":"JointLimitState2D","children":null},
		{"link":"JointProjectionMode","title":"JointProjectionMode","children":null},
		{"link":"KeyCode","title":"KeyCode","children":null},
		{"link":"LightmapsMode","title":"LightmapsMode","children":null},
		{"link":"LightRenderMode","title":"LightRenderMode","children":null},
		{"link":"LightShadows","title":"LightShadows","children":null},
		{"link":"LightType","title":"LightType","children":null},
		{"link":"LocationServiceStatus","title":"LocationServiceStatus","children":null},
		{"link":"LogType","title":"LogType","children":null},
		{"link":"MasterServerEvent","title":"MasterServerEvent","children":null},
		{"link":"MeshTopology","title":"MeshTopology","children":null},
		{"link":"NavMeshPathStatus","title":"NavMeshPathStatus","children":null},
		{"link":"NetworkConnectionError","title":"NetworkConnectionError","children":null},
		{"link":"NetworkDisconnection","title":"NetworkDisconnection","children":null},
		{"link":"NetworkLogLevel","title":"NetworkLogLevel","children":null},
		{"link":"NetworkPeerType","title":"NetworkPeerType","children":null},
		{"link":"NetworkReachability","title":"NetworkReachability","children":null},
		{"link":"NetworkStateSynchronization","title":"NetworkStateSynchronization","children":null},
		{"link":"NPOTSupport","title":"NPOTSupport","children":null},
		{"link":"ObstacleAvoidanceType","title":"ObstacleAvoidanceType","children":null},
		{"link":"OffMeshLinkType","title":"OffMeshLinkType","children":null},
		{"link":"ParticleRenderMode","title":"ParticleRenderMode","children":null},
		{"link":"ParticleSystemRenderMode","title":"ParticleSystemRenderMode","children":null},
		{"link":"ParticleSystemSimulationSpace","title":"ParticleSystemSimulationSpace","children":null},
		{"link":"PhysicMaterialCombine","title":"PhysicMaterialCombine","children":null},
		{"link":"PlayMode","title":"PlayMode","children":null},
		{"link":"PrimitiveType","title":"PrimitiveType","children":null},
		{"link":"ProceduralCacheSize","title":"ProceduralCacheSize","children":null},
		{"link":"ProceduralLoadingBehavior","title":"ProceduralLoadingBehavior","children":null},
		{"link":"ProceduralOutputType","title":"ProceduralOutputType","children":null},
		{"link":"ProceduralProcessorUsage","title":"ProceduralProcessorUsage","children":null},
		{"link":"ProceduralPropertyType","title":"ProceduralPropertyType","children":null},
		{"link":"QueueMode","title":"QueueMode","children":null},
		{"link":"RectTransform.Axis","title":"Axis","children":null},
		{"link":"RectTransform.Edge","title":"Edge","children":null},
		{"link":"RemoteNotificationType","title":"RemoteNotificationType","children":null},
		{"link":"RenderingPath","title":"RenderingPath","children":null},
		{"link":"RenderMode","title":"RenderMode","children":null},
		{"link":"RenderTextureFormat","title":"RenderTextureFormat","children":null},
		{"link":"RenderTextureReadWrite","title":"RenderTextureReadWrite","children":null},
		{"link":"RigidbodyConstraints","title":"RigidbodyConstraints","children":null},
		{"link":"RigidbodyInterpolation","title":"RigidbodyInterpolation","children":null},
		{"link":"RigidbodyInterpolation2D","title":"RigidbodyInterpolation2D","children":null},
		{"link":"RigidbodySleepMode2D","title":"RigidbodySleepMode2D","children":null},
		{"link":"RotationDriveMode","title":"RotationDriveMode","children":null},
		{"link":"RPCMode","title":"RPCMode","children":null},
		{"link":"RuntimePlatform","title":"RuntimePlatform","children":null},
		{"link":"SamsungTV.TouchPadMode","title":"TouchPadMode","children":null},
		{"link":"ScaleMode","title":"ScaleMode","children":null},
		{"link":"ScreenOrientation","title":"ScreenOrientation","children":null},
		{"link":"SendMessageOptions","title":"SendMessageOptions","children":null},
		{"link":"ShadowProjection","title":"ShadowProjection","children":null},
		{"link":"SkinQuality","title":"SkinQuality","children":null},
		{"link":"Space","title":"Space","children":null},
		{"link":"SpriteAlignment","title":"SpriteAlignment","children":null},
		{"link":"SpriteMeshType","title":"SpriteMeshType","children":null},
		{"link":"SpritePackingMode","title":"SpritePackingMode","children":null},
		{"link":"SpritePackingRotation","title":"SpritePackingRotation","children":null},
		{"link":"SystemLanguage","title":"SystemLanguage","children":null},
		{"link":"TerrainRenderFlags","title":"TerrainRenderFlags","children":null},
		{"link":"TextAlignment","title":"TextAlignment","children":null},
		{"link":"TextAnchor","title":"TextAnchor","children":null},
		{"link":"TextClipping","title":"TextClipping","children":null},
		{"link":"TextEditor.DblClickSnapping","title":"DblClickSnapping","children":null},
		{"link":"TextureCompressionQuality","title":"TextureCompressionQuality","children":null},
		{"link":"TextureFormat","title":"TextureFormat","children":null},
		{"link":"TextureWrapMode","title":"TextureWrapMode","children":null},
		{"link":"ThreadPriority","title":"ThreadPriority","children":null},
		{"link":"TouchPhase","title":"TouchPhase","children":null},
		{"link":"TouchScreenKeyboardType","title":"TouchScreenKeyboardType","children":null},
		{"link":"TransparencySortMode","title":"TransparencySortMode","children":null},
		{"link":"UserAuthorization","title":"UserAuthorization","children":null},
		{"link":"VerticalWrapMode","title":"VerticalWrapMode","children":null},
		{"link":"WrapMode","title":"WrapMode","children":null}
	]
},
{"link":"null","title":"Attributes","children":
	[
			{"link":"ContextMenuItemAttribute","title":"ContextMenuItemAttribute","children":null},
		{"link":"HeaderAttribute","title":"HeaderAttribute","children":null},
		{"link":"ImplementedInActionScriptAttribute","title":"ImplementedInActionScriptAttribute","children":null},
		{"link":"MultilineAttribute","title":"MultilineAttribute","children":null},
		{"link":"NotConvertedAttribute","title":"NotConvertedAttribute","children":null},
		{"link":"NotFlashValidatedAttribute","title":"NotFlashValidatedAttribute","children":null},
		{"link":"NotRenamedAttribute","title":"NotRenamedAttribute","children":null},
		{"link":"PropertyAttribute","title":"PropertyAttribute","children":null},
		{"link":"RangeAttribute","title":"RangeAttribute","children":null},
		{"link":"SelectionBaseAttribute","title":"SelectionBaseAttribute","children":null},
		{"link":"SpaceAttribute","title":"SpaceAttribute","children":null},
		{"link":"TextAreaAttribute","title":"TextAreaAttribute","children":null},
		{"link":"ThreadSafeAttribute","title":"ThreadSafeAttribute","children":null},
		{"link":"TooltipAttribute","title":"TooltipAttribute","children":null}
	]
}
	]
},{"link":"null","title":"UnityEditor","children":
	[
		{"link":"null","title":"UnityEditor.AnimatedValues","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"AnimatedValues.AnimBool","title":"AnimBool","children":null},
			{"link":"AnimatedValues.AnimFloat","title":"AnimFloat","children":null},
			{"link":"AnimatedValues.AnimQuaternion","title":"AnimQuaternion","children":null},
			{"link":"AnimatedValues.AnimVector3","title":"AnimVector3","children":null},
			{"link":"AnimatedValues.BaseAnimValue_1","title":"BaseAnimValue<T0>","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.Callbacks","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"Callbacks.DidReloadScripts","title":"DidReloadScripts","children":null}
		]
	},
	{"link":"null","title":"Attributes","children":
		[
					{"link":"Callbacks.OnOpenAssetAttribute","title":"OnOpenAssetAttribute","children":null},
			{"link":"Callbacks.PostProcessBuildAttribute","title":"PostProcessBuildAttribute","children":null},
			{"link":"Callbacks.PostProcessSceneAttribute","title":"PostProcessSceneAttribute","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.Events","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"Events.UnityEventTools","title":"UnityEventTools","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.EventSystems","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"EventSystems.EventTriggerEditor","title":"EventTriggerEditor","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.Macros","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"Macros.MacroEvaluator","title":"MacroEvaluator","children":null},
			{"link":"Macros.MethodEvaluator","title":"MethodEvaluator","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.Sprites","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"Sprites.AtlasSettings","title":"AtlasSettings","children":null},
			{"link":"Sprites.Packer","title":"Packer","children":null},
			{"link":"Sprites.PackerJob","title":"PackerJob","children":null}
		]
	},
	{"link":"null","title":"Enumerations","children":
		[
					{"link":"Sprites.Packer.Execution","title":"Execution","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.UI","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"UI.AnimationTriggersDrawer","title":"AnimationTriggersDrawer","children":null},
			{"link":"UI.AspectRatioFitterEditor","title":"AspectRatioFitterEditor","children":null},
			{"link":"UI.ButtonEditor","title":"ButtonEditor","children":null},
			{"link":"UI.CanvasScalerEditor","title":"CanvasScalerEditor","children":null},
			{"link":"UI.ColorBlockDrawer","title":"ColorBlockDrawer","children":null},
			{"link":"UI.ContentSizeFitterEditor","title":"ContentSizeFitterEditor","children":null},
			{"link":"UI.EventSystemEditor","title":"EventSystemEditor","children":null},
			{"link":"UI.FontDataDrawer","title":"FontDataDrawer","children":null},
			{"link":"UI.GraphicEditor","title":"GraphicEditor","children":null},
			{"link":"UI.GridLayoutGroupEditor","title":"GridLayoutGroupEditor","children":null},
			{"link":"UI.HorizontalOrVerticalLayoutGroupEditor","title":"HorizontalOrVerticalLayoutGroupEditor","children":null},
			{"link":"UI.ImageEditor","title":"ImageEditor","children":null},
			{"link":"UI.InputFieldEditor","title":"InputFieldEditor","children":null},
			{"link":"UI.LayoutElementEditor","title":"LayoutElementEditor","children":null},
			{"link":"UI.NavigationDrawer","title":"NavigationDrawer","children":null},
			{"link":"UI.RawImageEditor","title":"RawImageEditor","children":null},
			{"link":"UI.ScrollbarEditor","title":"ScrollbarEditor","children":null},
			{"link":"UI.ScrollRectEditor","title":"ScrollRectEditor","children":null},
			{"link":"UI.SelectableEditor","title":"SelectableEditor","children":null},
			{"link":"UI.SelfControllerEditor","title":"SelfControllerEditor","children":null},
			{"link":"UI.SliderEditor","title":"SliderEditor","children":null},
			{"link":"UI.SpriteStateDrawer","title":"SpriteStateDrawer","children":null},
			{"link":"UI.TextEditor","title":"TextEditor","children":null},
			{"link":"UI.ToggleEditor","title":"ToggleEditor","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.VersionControl","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"VersionControl.Asset","title":"Asset","children":null},
			{"link":"VersionControl.AssetList","title":"AssetList","children":null},
			{"link":"VersionControl.ChangeSet","title":"ChangeSet","children":null},
			{"link":"VersionControl.ChangeSets","title":"ChangeSets","children":null},
			{"link":"VersionControl.ConfigField","title":"ConfigField","children":null},
			{"link":"VersionControl.Message","title":"Message","children":null},
			{"link":"VersionControl.Plugin","title":"Plugin","children":null},
			{"link":"VersionControl.Provider","title":"Provider","children":null},
			{"link":"VersionControl.Task","title":"Task","children":null}
		]
	},
	{"link":"null","title":"Enumerations","children":
		[
					{"link":"VersionControl.Asset.States","title":"States","children":null},
			{"link":"VersionControl.CheckoutMode","title":"CheckoutMode","children":null},
			{"link":"VersionControl.CompletionAction","title":"CompletionAction","children":null},
			{"link":"VersionControl.FileMode","title":"FileMode","children":null},
			{"link":"VersionControl.MergeMethod","title":"MergeMethod","children":null},
			{"link":"VersionControl.Message.Severity","title":"Severity","children":null},
			{"link":"VersionControl.OnlineState","title":"OnlineState","children":null},
			{"link":"VersionControl.ResolveMethod","title":"ResolveMethod","children":null},
			{"link":"VersionControl.RevertMode","title":"RevertMode","children":null},
			{"link":"VersionControl.SubmitResult","title":"SubmitResult","children":null}
		]
	}
		]
	},
{"link":"null","title":"Classes","children":
	[
			{"link":"AlphabeticalSort","title":"AlphabeticalSort","children":null},
		{"link":"AnimationClipCurveData","title":"AnimationClipCurveData","children":null},
		{"link":"AnimationClipSettings","title":"AnimationClipSettings","children":null},
		{"link":"AnimationMode","title":"AnimationMode","children":null},
		{"link":"AnimationUtility","title":"AnimationUtility","children":null},
		{"link":"ArrayUtility","title":"ArrayUtility","children":null},
		{"link":"AssetDatabase","title":"AssetDatabase","children":null},
		{"link":"AssetImporter","title":"AssetImporter","children":null},
		{"link":"AssetModificationProcessor","title":"AssetModificationProcessor","children":null},
		{"link":"AssetPostprocessor","title":"AssetPostprocessor","children":null},
		{"link":"AssetPreview","title":"AssetPreview","children":null},
		{"link":"AudioImporter","title":"AudioImporter","children":null},
		{"link":"BaseHierarchySort","title":"BaseHierarchySort","children":null},
		{"link":"BuildPipeline","title":"BuildPipeline","children":null},
		{"link":"CanEditMultipleObjects","title":"CanEditMultipleObjects","children":null},
		{"link":"CustomEditor","title":"CustomEditor","children":null},
		{"link":"CustomPropertyDrawer","title":"CustomPropertyDrawer","children":null},
		{"link":"DecoratorDrawer","title":"DecoratorDrawer","children":null},
		{"link":"DragAndDrop","title":"DragAndDrop","children":null},
		{"link":"DrawGizmo","title":"DrawGizmo","children":null},
		{"link":"Editor","title":"Editor","children":null},
		{"link":"EditorApplication","title":"EditorApplication","children":null},
		{"link":"EditorCurveBinding","title":"EditorCurveBinding","children":null},
		{"link":"EditorGUI","title":"EditorGUI","children":null},
		{"link":"EditorGUILayout","title":"EditorGUILayout","children":null},
		{"link":"EditorGUIUtility","title":"EditorGUIUtility","children":null},
		{"link":"EditorMaterialUtility","title":"EditorMaterialUtility","children":null},
		{"link":"EditorPrefs","title":"EditorPrefs","children":null},
		{"link":"EditorStyles","title":"EditorStyles","children":null},
		{"link":"EditorUserBuildSettings","title":"EditorUserBuildSettings","children":null},
		{"link":"EditorUtility","title":"EditorUtility","children":null},
		{"link":"EditorWindow","title":"EditorWindow","children":null},
		{"link":"FileUtil","title":"FileUtil","children":null},
		{"link":"GameObjectUtility","title":"GameObjectUtility","children":null},
		{"link":"GenericMenu","title":"GenericMenu","children":null},
		{"link":"GUIDrawer","title":"GUIDrawer","children":null},
		{"link":"Handles","title":"Handles","children":null},
		{"link":"HandleUtility","title":"HandleUtility","children":null},
		{"link":"Help","title":"Help","children":null},
		{"link":"Highlighter","title":"Highlighter","children":null},
		{"link":"LightmapEditorSettings","title":"LightmapEditorSettings","children":null},
		{"link":"Lightmapping","title":"Lightmapping","children":null},
		{"link":"LODUtility","title":"LODUtility","children":null},
		{"link":"MaterialEditor","title":"MaterialEditor","children":null},
		{"link":"MaterialProperty","title":"MaterialProperty","children":null},
		{"link":"MaterialPropertyDrawer","title":"MaterialPropertyDrawer","children":null},
		{"link":"MathUtils","title":"MathUtils","children":null},
		{"link":"MenuCommand","title":"MenuCommand","children":null},
		{"link":"MenuItem","title":"MenuItem","children":null},
		{"link":"MeshUtility","title":"MeshUtility","children":null},
		{"link":"ModelImporter","title":"ModelImporter","children":null},
		{"link":"ModelImporterClipAnimation","title":"ModelImporterClipAnimation","children":null},
		{"link":"MonoImporter","title":"MonoImporter","children":null},
		{"link":"MonoScript","title":"MonoScript","children":null},
		{"link":"MovieImporter","title":"MovieImporter","children":null},
		{"link":"NavMeshBuilder","title":"NavMeshBuilder","children":null},
		{"link":"ObjectNames","title":"ObjectNames","children":null},
		{"link":"ObjectPreview","title":"ObjectPreview","children":null},
		{"link":"ObjectReferenceKeyframe","title":"ObjectReferenceKeyframe","children":null},
		{"link":"PlayerSettings","title":"PlayerSettings","children":null},
		{"link":"PlayerSettings.Android","title":"Android","children":null},
		{"link":"PlayerSettings.BlackBerry","title":"BlackBerry","children":null},
		{"link":"PlayerSettings.iOS","title":"iOS","children":null},
		{"link":"PlayerSettings.PS3","title":"PS3","children":null},
		{"link":"PlayerSettings.SamsungTV","title":"SamsungTV","children":null},
		{"link":"PlayerSettings.Tizen","title":"Tizen","children":null},
		{"link":"PopupWindow","title":"PopupWindow","children":null},
		{"link":"PopupWindowContent","title":"PopupWindowContent","children":null},
		{"link":"PrefabUtility","title":"PrefabUtility","children":null},
		{"link":"PreferenceItem","title":"PreferenceItem","children":null},
		{"link":"ProjectWindowUtil","title":"ProjectWindowUtil","children":null},
		{"link":"PropertyDrawer","title":"PropertyDrawer","children":null},
		{"link":"PropertyModification","title":"PropertyModification","children":null},
		{"link":"SceneModeUtility","title":"SceneModeUtility","children":null},
		{"link":"SceneView.SceneViewState","title":"SceneViewState","children":null},
		{"link":"ScriptableWizard","title":"ScriptableWizard","children":null},
		{"link":"SearchableEditorWindow","title":"SearchableEditorWindow","children":null},
		{"link":"Selection","title":"Selection","children":null},
		{"link":"SerializedObject","title":"SerializedObject","children":null},
		{"link":"SerializedProperty","title":"SerializedProperty","children":null},
		{"link":"ShaderImporter","title":"ShaderImporter","children":null},
		{"link":"ShaderUtil","title":"ShaderUtil","children":null},
		{"link":"SpriteMetaData","title":"SpriteMetaData","children":null},
		{"link":"StaticOcclusionCulling","title":"StaticOcclusionCulling","children":null},
		{"link":"StaticOcclusionCullingVisualization","title":"StaticOcclusionCullingVisualization","children":null},
		{"link":"SubstanceArchive","title":"SubstanceArchive","children":null},
		{"link":"SubstanceImporter","title":"SubstanceImporter","children":null},
		{"link":"TextureImporter","title":"TextureImporter","children":null},
		{"link":"TextureImporterSettings","title":"TextureImporterSettings","children":null},
		{"link":"TextureImportInstructions","title":"TextureImportInstructions","children":null},
		{"link":"Tools","title":"Tools","children":null},
		{"link":"TransformSort","title":"TransformSort","children":null},
		{"link":"TrueTypeFontImporter","title":"TrueTypeFontImporter","children":null},
		{"link":"Undo","title":"Undo","children":null},
		{"link":"UndoPropertyModification","title":"UndoPropertyModification","children":null},
		{"link":"UnwrapParam","title":"UnwrapParam","children":null},
		{"link":"Unwrapping","title":"Unwrapping","children":null}
	]
},
{"link":"null","title":"Enumerations","children":
	[
			{"link":"AndroidBuildSubtarget","title":"AndroidBuildSubtarget","children":null},
		{"link":"AndroidPreferredInstallLocation","title":"AndroidPreferredInstallLocation","children":null},
		{"link":"AndroidSdkVersions","title":"AndroidSdkVersions","children":null},
		{"link":"AndroidShowActivityIndicatorOnLoading","title":"AndroidShowActivityIndicatorOnLoading","children":null},
		{"link":"AndroidSplashScreenScale","title":"AndroidSplashScreenScale","children":null},
		{"link":"AndroidTargetDevice","title":"AndroidTargetDevice","children":null},
		{"link":"AnimationUtility.CurveModifiedType","title":"CurveModifiedType","children":null},
		{"link":"ApiCompatibilityLevel","title":"ApiCompatibilityLevel","children":null},
		{"link":"AspectRatio","title":"AspectRatio","children":null},
		{"link":"AssetDeleteResult","title":"AssetDeleteResult","children":null},
		{"link":"AssetMoveResult","title":"AssetMoveResult","children":null},
		{"link":"AudioImporterFormat","title":"AudioImporterFormat","children":null},
		{"link":"AudioImporterLoadType","title":"AudioImporterLoadType","children":null},
		{"link":"BlackBerryBuildSubtarget","title":"BlackBerryBuildSubtarget","children":null},
		{"link":"BlackBerryBuildType","title":"BlackBerryBuildType","children":null},
		{"link":"BodyPart","title":"BodyPart","children":null},
		{"link":"BoneState","title":"BoneState","children":null},
		{"link":"BuildAssetBundleOptions","title":"BuildAssetBundleOptions","children":null},
		{"link":"BuildOptions","title":"BuildOptions","children":null},
		{"link":"BuildTarget","title":"BuildTarget","children":null},
		{"link":"BuildTargetGroup","title":"BuildTargetGroup","children":null},
		{"link":"ClipAnimationMaskType","title":"ClipAnimationMaskType","children":null},
		{"link":"D3D9FullscreenMode","title":"D3D9FullscreenMode","children":null},
		{"link":"DragAndDropVisualMode","title":"DragAndDropVisualMode","children":null},
		{"link":"DrawCameraMode","title":"DrawCameraMode","children":null},
		{"link":"EditorBehaviorMode","title":"EditorBehaviorMode","children":null},
		{"link":"EditorSkin","title":"EditorSkin","children":null},
		{"link":"ExportPackageOptions","title":"ExportPackageOptions","children":null},
		{"link":"FlashBuildSubtarget","title":"FlashBuildSubtarget","children":null},
		{"link":"FontRenderingMode","title":"FontRenderingMode","children":null},
		{"link":"FontTextureCase","title":"FontTextureCase","children":null},
		{"link":"GameViewSizeGroupType","title":"GameViewSizeGroupType","children":null},
		{"link":"GizmoType","title":"GizmoType","children":null},
		{"link":"HighlightSearchMode","title":"HighlightSearchMode","children":null},
		{"link":"IconDrawStyle","title":"IconDrawStyle","children":null},
		{"link":"ImportAssetOptions","title":"ImportAssetOptions","children":null},
		{"link":"iOSSdkVersion","title":"iOSSdkVersion","children":null},
		{"link":"iOSShowActivityIndicatorOnLoading","title":"iOSShowActivityIndicatorOnLoading","children":null},
		{"link":"iOSStatusBarStyle","title":"iOSStatusBarStyle","children":null},
		{"link":"iOSTargetDevice","title":"iOSTargetDevice","children":null},
		{"link":"iOSTargetOSVersion","title":"iOSTargetOSVersion","children":null},
		{"link":"iOSTargetResolution","title":"iOSTargetResolution","children":null},
		{"link":"LightmapBakeQuality","title":"LightmapBakeQuality","children":null},
		{"link":"MacFullscreenMode","title":"MacFullscreenMode","children":null},
		{"link":"MaterialProperty.PropFlags","title":"PropFlags","children":null},
		{"link":"MaterialProperty.PropType","title":"PropType","children":null},
		{"link":"MaterialProperty.TexDim","title":"TexDim","children":null},
		{"link":"MessageType","title":"MessageType","children":null},
		{"link":"ModelImporterAnimationCompression","title":"ModelImporterAnimationCompression","children":null},
		{"link":"ModelImporterAnimationType","title":"ModelImporterAnimationType","children":null},
		{"link":"ModelImporterGenerateAnimations","title":"ModelImporterGenerateAnimations","children":null},
		{"link":"ModelImporterMaterialName","title":"ModelImporterMaterialName","children":null},
		{"link":"ModelImporterMaterialSearch","title":"ModelImporterMaterialSearch","children":null},
		{"link":"ModelImporterMeshCompression","title":"ModelImporterMeshCompression","children":null},
		{"link":"ModelImporterTangentSpaceMode","title":"ModelImporterTangentSpaceMode","children":null},
		{"link":"MouseCursor","title":"MouseCursor","children":null},
		{"link":"PivotMode","title":"PivotMode","children":null},
		{"link":"PivotRotation","title":"PivotRotation","children":null},
		{"link":"PlayerSettings.MetroCompilationOverrides","title":"MetroCompilationOverrides","children":null},
		{"link":"PrefabType","title":"PrefabType","children":null},
		{"link":"PSP2BuildSubtarget","title":"PSP2BuildSubtarget","children":null},
		{"link":"RemoveAssetOptions","title":"RemoveAssetOptions","children":null},
		{"link":"ReplacePrefabOptions","title":"ReplacePrefabOptions","children":null},
		{"link":"ResolutionDialogSetting","title":"ResolutionDialogSetting","children":null},
		{"link":"SaveType","title":"SaveType","children":null},
		{"link":"SCEBuildSubtarget","title":"SCEBuildSubtarget","children":null},
		{"link":"ScriptCallOptimizationLevel","title":"ScriptCallOptimizationLevel","children":null},
		{"link":"SearchableEditorWindow.SearchMode","title":"SearchMode","children":null},
		{"link":"SearchableEditorWindow.SearchModeHierarchyWindow","title":"SearchModeHierarchyWindow","children":null},
		{"link":"SelectionMode","title":"SelectionMode","children":null},
		{"link":"SerializedPropertyType","title":"SerializedPropertyType","children":null},
		{"link":"ShaderUtil.ShaderPropertyTexDim","title":"ShaderPropertyTexDim","children":null},
		{"link":"ShaderUtil.ShaderPropertyType","title":"ShaderPropertyType","children":null},
		{"link":"SpriteImportMode","title":"SpriteImportMode","children":null},
		{"link":"SpritePackerMode","title":"SpritePackerMode","children":null},
		{"link":"StaticEditorFlags","title":"StaticEditorFlags","children":null},
		{"link":"StrippingLevel","title":"StrippingLevel","children":null},
		{"link":"TargetGlesGraphics","title":"TargetGlesGraphics","children":null},
		{"link":"TextureImporterFormat","title":"TextureImporterFormat","children":null},
		{"link":"TextureImporterGenerateCubemap","title":"TextureImporterGenerateCubemap","children":null},
		{"link":"TextureImporterMipFilter","title":"TextureImporterMipFilter","children":null},
		{"link":"TextureImporterNormalFilter","title":"TextureImporterNormalFilter","children":null},
		{"link":"TextureImporterNPOTScale","title":"TextureImporterNPOTScale","children":null},
		{"link":"TextureImporterType","title":"TextureImporterType","children":null},
		{"link":"TizenBuildSubtarget","title":"TizenBuildSubtarget","children":null},
		{"link":"Tool","title":"Tool","children":null},
		{"link":"UIOrientation","title":"UIOrientation","children":null},
		{"link":"ViewTool","title":"ViewTool","children":null},
		{"link":"XboxBuildSubtarget","title":"XboxBuildSubtarget","children":null},
		{"link":"XboxOneRunMethod","title":"XboxOneRunMethod","children":null},
		{"link":"XboxRunMethod","title":"XboxRunMethod","children":null}
	]
},
{"link":"null","title":"Attributes","children":
	[
			{"link":"CallbackOrderAttribute","title":"CallbackOrderAttribute","children":null},
		{"link":"CustomPreviewAttribute","title":"CustomPreviewAttribute","children":null},
		{"link":"InitializeOnLoadAttribute","title":"InitializeOnLoadAttribute","children":null}
	]
}
	]
},{"link":"null","title":"Other","children":
	[
	{"link":"null","title":"Classes","children":
	[
			{"link":"Array","title":"Array","children":null},
		{"link":"Hashtable","title":"Hashtable","children":null},
		{"link":"NonSerializable","title":"NonSerializable","children":null},
		{"link":"Path","title":"Path","children":null},
		{"link":"Serializable","title":"Serializable","children":null},
		{"link":"String","title":"String","children":null}
	]
}
	]
}]}